#!/bin/sh
#
# AUDIT TRAIL: 1.3
# 1. RLZ   06/12/2006        Initial Verison
#
# AUDIT TRAIL: 1.4
# 1. RLZ   04/17/2007        Added new cube WFT_ACADEMIC_PROGRAM_COURSE
#
# AUDIT TRAIL: 8.1
# 1. Added new Financial Aid cubes.                       SPC 02/10/2009
#
# AUDIT TRAIL END
#
# FILE NAME..: deployEDWCubes
# PRODUCT....: INFROMATION ACCESS
# USAGE......: Driver script for deploying EDW cubes
#
# COPYRIGHT..: Copyright (c) SCT Corporation 2004.  All rights reserved.
#
#-----------------------------------------------------------
# Parameters:
#    1 - cube file name
#-----------------------------------------------------------

. ./setUpCognosEnv

#--------------------------------------------------------------------------
# Stop Cognos 8 service
#--------------------------------------------------------------------------


echo Stopping Cognos 8 service ...........
cd $COGNOS_ROOT_DIR/bin/
./cogconfig.sh -stop

#--------------------------------------------------------------------------
# Update Cognos cubes
#--------------------------------------------------------------------------

# Uncomment the line for the cube(s) you want to rebuild.
cd $TRANSFORMER_SCRIPTS_DIR

./updateCognosCube WFT_ENROLLMENT                   
./updateCognosCube WFT_RECRUITING_AND_ADMISSION     
./updateCognosCube WFT_COURSE_REGISTRATION          
./updateCognosCube WFT_GRADUATION_COMPLETION        
./updateCognosCube WFT_FINANCIAL_AID_STUDENT        
./updateCognosCube WFT_FINANCIAL_AID_PRE_STUDENT    
./updateCognosCube WFT_OPERATING_LEDGER             
./updateCognosCube WFT_GENERAL_LEDGER               
./updateCognosCube WFT_GENERAL_LEDGER_EVENT          
./updateCognosCube WFT_RECEIVABLE_CUSTOMER          
./updateCognosCube WFT_RECEIVABLE_REVENUE           
./updateCognosCube WFT_GRANT_AND_PROJECT            
./updateCognosCube WFT_EMPLOYEE                     
./updateCognosCube WFT_EMPLOYEE_POSITION            
./updateCognosCube WFT_EMPLOYEE_DEGREE              
./updateCognosCube WFT_EMPLOYMENT_APPLICATION
./updateCognosCube WFT_ADVANCEMENT_GIFT
./updateCognosCube WFT_ACADEMIC_PROGRAM_COURSE           
./updateCognosCube PM_Admissions_Counselor_Cube_Current_Academic_Period
./updateCognosCube PM_Admissions_Counselor_Cube
./updateCognosCube PM_Aid_Impact_Analysis_Cube_Current_Academic_Period
./updateCognosCube PM_Aid_Impact_Analysis_Cube
./updateCognosCube PM_Award_Analysis_Cube_Current_Academic_Period
./updateCognosCube PM_Award_Analysis_Cube

# 
#
#--------------------------------------------------------------------------
# restart Cognos 8 service
#--------------------------------------------------------------------------

echo Starting Cognos 8 service ..........
cd $COGNOS_ROOT_DIR/bin/
./cogconfig.sh -s
